/*
 * LoansSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:41 PM
 */

package net.abbht.lamo.bo.loans;

import junit.framework.*;

/**
 *
 * @author home
 */
public class LoansSuite extends TestCase {
    
    public LoansSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("LoansSuite");
        suite.addTest(net.abbht.lamo.bo.loans.LoanBOImplTest.suite());
        suite.addTest(net.abbht.lamo.bo.loans.ValidateItemTest.suite());
        suite.addTest(net.abbht.lamo.bo.loans.ValidateRenewTest.suite());
        suite.addTest(net.abbht.lamo.bo.loans.LoanBOFactoryTest.suite());
        suite.addTest(net.abbht.lamo.bo.loans.ValidateUserTest.suite());
        suite.addTest(net.abbht.lamo.bo.loans.LoanBOTest.suite());
        return suite;
    }
    
}
