/*
 * LamoSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:42 PM
 */

package net.abbht.lamo;

import junit.framework.*;

/**
 *
 * @author home
 */
public class LamoSuite extends TestCase {
    
    public LamoSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("LamoSuite");
        suite.addTest(net.abbht.lamo.bo.BoSuite.suite());
        suite.addTest(net.abbht.lamo.utils.UtilsSuite.suite());
        suite.addTest(net.abbht.lamo.facades.FacadesSuite.suite());
        suite.addTest(net.abbht.lamo.persistence.PersistenceSuite.suite());
        return suite;
    }
    
}
