/*
 * ItemsSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:41 PM
 */

package net.abbht.lamo.facades.items;

import junit.framework.*;

/**
 *
 * @author home
 */
public class ItemsSuite extends TestCase {
    
    public ItemsSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ItemsSuite");
        suite.addTest(net.abbht.lamo.facades.items.ItemFacadeTest.suite());
        suite.addTest(net.abbht.lamo.facades.items.DepartmentFacadeTest.suite());
        suite.addTest(net.abbht.lamo.facades.items.ItemGroupFacadeTest.suite());
        suite.addTest(net.abbht.lamo.facades.items.ItemTypesFacadeTest.suite());
        suite.addTest(net.abbht.lamo.facades.items.AuthorFacadeTest.suite());
        return suite;
    }
    
}
