/*
 * BoSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:41 PM
 */

package net.abbht.lamo.bo;

import junit.framework.*;

/**
 *
 * @author home
 */
public class BoSuite extends TestCase {
    
    public BoSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("BoSuite");
        suite.addTest(net.abbht.lamo.bo.users.UsersSuite.suite());
        suite.addTest(net.abbht.lamo.bo.items.ItemsSuite.suite());
        suite.addTest(net.abbht.lamo.bo.loans.LoansSuite.suite());
        suite.addTest(net.abbht.lamo.bo.utils.UtilsSuite.suite());
        return suite;
    }
    
}
