/*
 * PersistenceSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:42 PM
 */

package net.abbht.lamo.persistence;

import junit.framework.*;

/**
 *
 * @author home
 */
public class PersistenceSuite extends TestCase {
    
    public PersistenceSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("PersistenceSuite");
        suite.addTest(net.abbht.lamo.persistence.items.ItemsSuite.suite());
        suite.addTest(net.abbht.lamo.persistence.users.UsersSuite.suite());
        suite.addTest(net.abbht.lamo.persistence.loans.LoansSuite.suite());
        return suite;
    }
    
}
