/*
 * FacadesSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:41 PM
 */

package net.abbht.lamo.facades;

import junit.framework.*;

/**
 *
 * @author home
 */
public class FacadesSuite extends TestCase {
    
    public FacadesSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("FacadesSuite");
        suite.addTest(net.abbht.lamo.facades.items.ItemsSuite.suite());
        suite.addTest(net.abbht.lamo.facades.loans.LoansSuite.suite());
        suite.addTest(net.abbht.lamo.facades.users.UsersSuite.suite());
        return suite;
    }
    
}
