/*
 * UtilsSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:41 PM
 */

package net.abbht.lamo.utils;

import junit.framework.*;

/**
 *
 * @author home
 */
public class UtilsSuite extends TestCase {
    
    public UtilsSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("UtilsSuite");
        suite.addTest(net.abbht.lamo.utils.HibernateUtilTest.suite());
        suite.addTest(net.abbht.lamo.utils.SpringFactoryTest.suite());
        return suite;
    }
    
}
