import junit.framework.*;
/*
 * RootSuite.java
 * JUnit based test
 *
 * Created on December 10, 2006, 6:42 PM
 */

/**
 *
 * @author home
 */
public class RootSuite extends TestCase {
    
    public RootSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("RootSuite");
        suite.addTest(lib1.Lib1Suite.suite());
        suite.addTest(net.NetSuite.suite());
        return suite;
    }
    
}
